moving eslint to extension
ZakMiller/TheEmpire pull request #32
Opened 2017-02-08 13:51 UTC by ZakMiller

2017-02-09 04:26 UTC, SylvanSign commented on gulpfile.js
> +function watch () {
I'm not a fan of the space before function parens. Are you?

2017-02-09 04:27 UTC, SylvanSign commented on gulpfile.js
> +function watch () {
I'd prefer to add this to the `.eslintrc.js`:
```json

  "rules": {
    "space-before-function-paren": ["error", "never"]
  }

2017-02-09 04:27 UTC, SylvanSign requested changes
.

2017-02-09 12:25 UTC, ZakMiller commented on gulpfile.js
> +function watch () {
Hmm... it's detecting it as an error now, but it's not autofixing. Any idea why?

2017-02-09 14:32 UTC, SylvanSign commented on gulpfile.js
> +function watch () {
Yeah. You actually have to change the file in order for the linter to run on save, it seems. Just add a space somewhere, then save.

2017-02-10 01:43 UTC, SylvanSign requested changes

2017-02-10 01:43 UTC, SylvanSign commented on README.md
> +``` sh
sh means shell. You want json I think

2017-02-10 01:48 UTC, SylvanSign approved these changes

2017-02-10 01:50 UTC, merged