Role Distribution
ZakMiller/TheEmpire pull request #37
Opened 2017-02-19 19:58 UTC by ZakMiller

2017-02-20 07:23 UTC, SylvanSign requested changes

2017-02-20 07:23 UTC, SylvanSign commented on public/scripts/roles.js
> +    description: "You can say whatever you want, but be careful! If the robots figure out you're human it 's all over!"
It 's

2017-02-20 07:23 UTC, SylvanSign commented on server.js
> +      assignRoles(currentRoom)
This is in the wrong place. We only want to assign roles after the game state event has been emitted, so it should be executed some time right after a successful countdown and a start of game

2017-02-20 07:23 UTC, SylvanSign commented on server.js
> +  io.in(currentRoom).clients((err, clients) => {
`.in` and `.to` mean the same, but I think I like `.to` better, and you use it more often as well. Can we stick to just that one?

2017-02-20 07:23 UTC, SylvanSign commented on public/scripts/main.js
> +function displayRole(role) {
You can destructive this parameter into the three fields you need below. That's optional tho

2017-02-20 07:24 UTC, SylvanSign commented on public/scripts/main.js
> +function displayRole(role) {
Destructure

2017-02-20 19:20 UTC, SylvanSign commented on public/scripts/main.js
>      requiredWords.addWords(STARTING_REQUIRED_WORD_COUNT)
This adding of words is only needed for the AI, right? Can you fix this up as part of these changes?

2017-02-21 00:36 UTC, ZakMiller commented on server.js
> +  io.in(currentRoom).clients((err, clients) => {
I think it depends on the situation...
Here I think 'in' makes sense. You are saying io. in current room . clients. In other situations I think 'to' makes sense.

2017-02-21 00:38 UTC, ZakMiller commented on public/scripts/main.js
>      requiredWords.addWords(STARTING_REQUIRED_WORD_COUNT)
Ya good point. Hadn't thought of that.

2017-02-21 00:40 UTC, ZakMiller commented on server.js
> +      assignRoles(currentRoom)
How would you do it?

2017-02-21 03:26 UTC, SylvanSign commented on server.js
> +      assignRoles(currentRoom)
Put it within `startGame()`, but only call it after the game has actually started, not when we've started the countdown to a game. You're just calling it in the wrong place.

2017-02-21 03:43 UTC, SylvanSign commented on server.js
> +  io.in(currentRoom).clients((err, clients) => {
I gotcha. Fine with me then

2017-02-21 13:44 UTC, ZakMiller commented on public/scripts/main.js
>      requiredWords.addWords(STARTING_REQUIRED_WORD_COUNT)
Done

2017-02-21 14:13 UTC, SylvanSign approved these changes

2017-02-21 14:13 UTC, SylvanSign commented
Ready for merge?

2017-02-22 01:05 UTC, merged